version: "3.9"

services:
  user-node-app:
    build: .
    container_name: user-node-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URL_DB: mongodb://user:password@mongodb:27017/admin
      PORT: 3000
    volumes:
      - .:/app
    networks:
      - user-network

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - user-network

volumes:
  mongodb_data:


networks:
  user-network:
    driver: bridge
